#index:
#    path: /cat
#    controller: App\Controller\TypeCats::cat

#path_cat:
#    path: /cat
#    controller:  App\Controller\TypeCats::cat

#controllers:
#    resource:
#        path: \cat
#        namespace: App\Controller
#    type: attribute
#
#kernel:
#    resource: App\Kernel
#    type: attribute


